### ISSUE TITLE
Exposing console on microshift doesn't work

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#1012]
**Describe the bug**
When trying deploying a broker with expose console on microshift default installtion the the broker instance is not created. 

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  console:
    expose: true
```

Looking in the activemqartemis object, the status say:
```
  message: .Spec.Console has invalid ingress settings, IngressHost unspecified and no Spec.IngressDomain default domain provided
  observedGeneration: 1
  reason: InvalidIngressSettings
  status: "False"
  type: Valid
```

> [!TIP]
> Vote this issue reacting with :+1: or :-1:
