### ISSUE TITLE
Add disableStompServerHeader to acceptor into broker.xml

### ISSUE THREAD

**Issue by Sirol90** [artemiscloud/activemq-artemis-operator#1072]
**Add disableStompServerHeader to acceptor into broker.xml**
Can you add into the ActiveMQ Artemis a way for add the properties disableStompServerHeader please?   
I have try to used the brokerProperties but without success.   

Thenks,
Loris Montagna

**Comment by brusdev** [comment]
@Sirol90 have you already tried to set the acceptor params by suing broker properties?
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 1
  acceptors:
    - name: stomp
      port: 61617
  brokerProperties:
    - "acceptorConfigurations.stomp.params.disableStompServerHeader=true"
```

**Comment by Sirol90** [comment]
@brusdev yes but this no set the property on acceptor into broker.xml

This is the yaml i used for craete the broker:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: activemq-artemis-operator
spec:
  ingressDomain: test.local
  brokerProperties:
    - "acceptorConfigurations.artemis.params.disableStompServerHeader=true"
    - "acceptorConfigurations.stomp.params.disableStompServerHeader=true"
  deploymentPlan:
    size: 2
    messageMigration: true
    persistenceEnabled: false
    enableMetricsPlugin: true
    resources:
      limits:
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "1Gi"
    extraMounts:
      secrets:
        - artemis-broker-jaas-config
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "8161"
      prometheus.io/scrape: "true"
  acceptors:
    - name: artemis
      protocols: CORE,STOMP
  addressSettings:
    addressSetting:
      - match: '#'
        autoDeleteAddresses: true
  resourceTemplates:
   - selector:
       kind: "Ingress"
     annotations:
       kubernetes.io/ingress.class: "nginx"
  console:
    expose: true
    name: console
    ingressHost: $(CR_NAME)-$(ITEM_NAME)-$(BROKER_ORDINAL).$(INGRESS_DOMAIN)
```
And this is the broker.xml generated into the pod
```
<acceptor name="artemis">tcp://artemis-broker-ss-0.artemis-broker-hdls-svc.activemq-artemis-operator.svc.cluster.local:61626?protocols=CORE,STOMP;tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;useEpoll=true;amqpCredits=1000;amqpMinCredits=300</acceptor><acceptor name="scaleDown">tcp://artemis-broker-ss-0.artemis-broker-hdls-svc.activemq-artemis-operator.svc.cluster.local:61616?protocols=CORE;tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;useEpoll=true;amqpCredits=1000;amqpMinCredits=300</acceptor>
      </acceptors>
```
