### ISSUE TITLE
Artemis in kubernetes cluster doesn't start with persistance enabled equal to true

### ISSUE THREAD

**Issue by SamueleAlpino** [artemiscloud/activemq-artemis-operator#187]
After project cloning  https://github.com/artemiscloud/activemq-artemis-operator , I used the deploy-dry-run command to generate .yaml file to use inside my Kubernetes cluster, then I created a simple broker file using last images (the problem is present also using image: Placeholder ) , here the .yaml:
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: amq-artemis
  namespace: activemq-artemis-operator
spec:
  deploymentPlan:
    size: 3
    initImage: quay.io/artemiscloud/activemq-artemis-broker-init:1.0.0
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.0
    requireLogin: false
    persistenceEnabled: true
    messageMigration: true
  console:
    expose: true
    useClientAuth: false

Result: 
- The operator say that v1beta1.ActiveMQ ArtemisScaledown is not convertible to *v2 alpha1.ActiveMQ ArtemisScaledown
- The broker remains in 0/1 and it logs this :
 Failed to invoke setter setFileName with value /opt/amq-artemis/data/log/artemis.log  amq-artemis-ss-0 amq-artemis-container .java.lang.reflect.InvocationTargetException; 
…..
 WARN  [org.apache.activemq.artemis.core.server] AMQ222141: Node Manager can not open file /opt/amq-artemis/data/journal/server.lock: java.io.IOException: No such file or directory
  at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method) [java.base:]  
  at java.base java.io.File.createNewFile(File.java:1035) [java.base:]

This problem is caused by the  “persistenceEnabled: true” because if I set to false the persistence everything is well created and inside the pod I can see without problems the data directory.
Have you some hints on the cause or how to solve this?

**Comment by gaohoward** [comment]
@SamueleAlpino Hi can you try the latest operator? some wehook issue has just been fixed on main.

**Comment by ricardclau** [comment]
Hi, have the same issue as @SamueleAlpino. Do you mean trying with dev.latest? 

That one seems to be from a week ago, last merge to main did not build properly https://github.com/artemiscloud/activemq-artemis-operator/actions/runs/2090370365

**Comment by ricardclau** [comment]
I think this should help fixing it as it looks like permissions problems https://github.com/artemiscloud/activemq-artemis-operator/pull/123 and can be (for now) worked around https://github.com/artemiscloud/activemq-artemis-operator/issues/52

**Comment by brusdev** [comment]
Cannot reproduce on 1.0.17

**Comment by ColbyReed** [comment]
This is still happening in 1.1.0. Was able to resolve by adding the following to the deploymentPlan spec
`podSecurityContext:
      fsGroup: 0`

**Comment by brusdev** [comment]
> This is still happening in 1.1.0. Was able to resolve by adding the following to the deploymentPlan spec `podSecurityContext: fsGroup: 0`

@ColbyReed what broker version are you usign? Could you share your ActiveMQArtemis CR?

**Comment by ColbyReed** [comment]
> > This is still happening in 1.1.0. Was able to resolve by adding the following to the deploymentPlan spec `podSecurityContext: fsGroup: 0`
> 
> @ColbyReed what broker version are you usign? Could you share your ActiveMQArtemis CR?

I was using artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.32.0

CR:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: activemq-artemis
spec:
  acceptors:
    - expose: true
      name: artemis
      port: 61616
      protocols: all
  adminPassword: <admin-password>
  adminUser: <admin>
  brokerProperties:
    - metricsConfiguration.jvmGc=true
    - metricsConfiguration.jvmMemory=true
    - metricsConfiguration.jvmThread=true
  console:
    expose: true
    ingressHost: <url>
  deploymentPlan:
    enableMetricsPlugin: true
    image: >-
      <repo>/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.32.0
    initImage: >-
      <repo>/artemiscloud/activemq-artemis-broker-init:artemis.2.32.0
    messageMigration: true
    persistenceEnabled: true
    podSecurityContext:
      fsGroup: 0
    resources:
      limits:
        cpu: 1000m
        memory: 1500Mi
    size: 2
```
