### ISSUE TITLE
annotations in securty cr that are not shell safe can lead to crashbackoffloop on init container start

### ISSUE THREAD

**Issue by gtully** [artemiscloud/activemq-artemis-operator#211]
CR:

```
apiVersion: broker.amq.io/v1alpha1
kind: ActiveMQArtemisSecurity
metadata:
  annotations:
    testannotation: '"pltf-amq (1)"' 
```

that ends up in an unescaped argument to the configuration tool which errors out with:

```
/bin/bash: -c: line 16: syntax error near unexpected token `('
/bin/bash: -c: line 16: `    testannotation: '"pltf-amq (1)"'' 
```
