### ISSUE TITLE
UI access

### ISSUE THREAD

**Issue by mraslam** [artemiscloud/activemq-artemis-operator#214]
Is there a possibility to access the UI from within a kubernetes cluster?

**Comment by gaohoward** [comment]
The artemis broker comes with a admin console that you can use. Configure the broker CR with "console/expose" set to true and the operator will create an ingress for you (for k8s) or a route (for openshift). which allows you to visit the admin console.

**Comment by mraslam** [comment]
@gaohoward Thank you for the response. Will give it a try.

**Comment by lultala** [comment]
> The artemis broker comes with a admin console that you can use. Configure the broker CR with "console/expose" set to true and the operator will create an ingress for you (for k8s) or a route (for openshift). which allows you to visit the admin console.

in what file i must add this parametr

**Comment by brusdev** [comment]
The `console/expose` property is defined in the ActiveMQArtemis CRD, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-cert-broker
spec:
  deploymentPlan:
    size: 1
  console:
    expose: true
```
