### ISSUE TITLE
Enabling Persistence results in readinessProbe failing

### ISSUE THREAD

**Issue by kahootali** [artemiscloud/activemq-artemis-operator#283]
**Describe the bug**
If I enable persistence, the readinessProbe fails and never passes
I am using operator version 1.0.4 also tried with 1.03 and 1.0.2.
Kubernetes: `1.22`

I deployed the operator running the commands given

```sh
# Crds
kubectl create -f ./crds
# Resources
kubectl create -f ./deploy/service_account.yaml -n activemq
kubectl create -f ./deploy/role.yaml -n activemq
kubectl create -f ./deploy/role_binding.yaml -n activemq
kubectl create -f ./deploy/election_role.yaml -n activemq
kubectl create -f ./deploy/election_role_binding.yaml -n activemq
kubectl create -f ./deploy/operator_config.yaml -n activemq
kubectl create -f ./deploy/operator.yaml -n activemq
```

and then deployed using the official examples in the repo given 

```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 2
    image: placeholder
    persistenceEnabled: true
    messageMigration: true
```

it creates a StatefulSet but the readiness probe of 1st replica never passes so the 2nd replica never comes up, and it stays like that. I have also used 1 replica to disable clustering but still same issue

**Screenshots**
<img width="724" alt="image" src="https://user-images.githubusercontent.com/13013437/184632999-af0d3b29-350a-4f58-9b2e-5fc289f2c6d5.png">
