### ISSUE TITLE
Cannot create deadletterqueue from ActiveMQArtemis

### ISSUE THREAD

**Issue by duccaominh** [artemiscloud/activemq-artemis-operator#294]
Hi, i try to automatically create the dead letter queue using `autoCreateDeadLetterResources` for my `Topic.subscription.order` but artemis cloud keep saying the below error
`[13:38:07] [ERROR] yacfg :: Unable to find a requested profile "artemis//default_with_user_address_settings.yaml.jinja2"`

This is my yaml
```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: artemis
spec:
  console:
    expose: true
  deploymentPlan:
    messageMigration: true
    persistenceEnabled: true
    size: 1
  addressSettings:
    addressSetting:
      - autoCreateDeadLetterResources: true
        deadLetterAddress: testing
        defaultConsumerWindowSize: 2048000
        match: Topic.subscription.order
        maxDeliveryAttempts: 3
        maxSizeBytes: 10m
        configDeleteDiverts: 'off'
      - autoCreateDeadLetterResources: true
        autoCreateExpiryResources: true
        deadLetterQueueSuffix: .eq
        expiryQueueSuffix: .eq
        maxSizeBytes: '52428800'
        redeliveryDelay: 1000
        match: '#'
    applyRule: replace-all

```
