### ISSUE TITLE
Enhance the list of attributes for creating storage

### ISSUE THREAD

**Issue by Mohanavalli-A** [artemiscloud/activemq-artemis-operator#311]
Hi Team,

I want to use AzureFile storage as a custom StorageClass to store the broker data and logs.  Can you please provide attributes to specify the storage account to be used and the PV naming format, by adding the following fields under storage.

storageAccountName - To specify a name for the Storage account under which the PV has to be created. Example: `storageAccountName: broker-storage`

pvNamePrefix - To specify a constant prefix for the PV names that are created. The actual PV name should be {pvNamePrefix}-pv-{index}. Example: `pvNamePrefix : test-artemis-broker`, and the PVs as per the artemis stateful set should be created as `test-artemis-broker-pv-0`.
```
deploymentPlan:
  storage:
    size: "5Gi"
    storageClassName: azureFile
    storageAccountName: <To be added> 
    pvNamePrefix: <To be added>
```

Thanks.
