### ISSUE TITLE
Error setting the application label

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#340]
Setting the application label causes the following error:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    image: placeholder
    labels:
      application: test
```
```
ERROR    package k8s_actions    Failed to create new *v1.StatefulSet    {"ActiveMQArtemis Name": "ex-aao-ss", "Namespace": "test-namespace", "error": "StatefulSet.apps \"ex-aao-ss\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"ActiveMQArtemis\":\"ex-aao\", \"application\":\"test\"}: `selector` does not match template `labels`"}
```
