### ISSUE TITLE
Question: Message redistribution and client connection handling.

### ISSUE THREAD

**Issue by sachinsaju** [artemiscloud/activemq-artemis-operator#350]
I have a producer app P and consumer app C. I have a three replica pod setup created by artemis operator.

Questions:
1. I see a headless service name and service names for each pod in k8s services. Which service name should I use in order to connect from P and C? I want the load to be balanced for the pods. All queues I use are created at run time.

2. I tried to verify message redistribution. So I connected P to artemis pod 0 and C to artemis pod 1. But even though consumer and producer are using same queue name to send messages, consumer is not getting messages. When I checked, messages are present in pod 0.(They are not replicated or distributed to pod 1 even a Consumer is connected to pod 1).I had applied the settings redelivery delay to 0 and message-load-balancing to ON_DEMAND.

3. I miss messages because of the earlier mentioned scenario. I tried creating custom k8s service for client connections but it randomly connects to any of the 3 pods. So what should I do in order to make consumer and producer connect to same queue in same broker pod? 

4. Do artemis operator provide replication of messages in each broker pod for same queue address? 

Thanks a lot.

**Comment by brusdev** [comment]
Cannot reproduce on 1.0.17

**Comment by teksuo** [comment]
Is there any way of setting the `message-load-balancing` to STRICT ?

**Comment by brusdev** [comment]
> Is there any way of setting the `message-load-balancing` to STRICT ?

@teksuo you can set the `message-load-balancing` of the default cluster connection to STRICT by using broker properties, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  brokerProperties:
    - "clusterConfigurations.my-cluster.messageLoadBalancingType=STRICT"
```
