### ISSUE TITLE
Generated install file cluster_role_binding.yaml misses subject namespace field

### ISSUE THREAD

**Issue by michalxo** [artemiscloud/activemq-artemis-operator#361]
Expected output yaml contains `./subject/namespace` path. Currently it is missing after latest merged PRs.
```
deployment.apps/activemq-artemis-controller-manager created
The ClusterRoleBinding "activemq-artemis-operator-rolebinding" is invalid: subjects[0].namespace: Required value
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: activemq-artemis-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: activemq-artemis-operator
subjects:
- kind: ServiceAccount
  name: activemq-artemis-controller-manager
  namespace: my-test-namespace
```
