### ISSUE TITLE
How to setup security with secrets

### ISSUE THREAD

**Issue by sebastien-comeau** [artemiscloud/activemq-artemis-operator#398]
I'm trying to add security when deploying Artemis. The application require login have access. I'm using `propertiesLoginModules` but at the moment my user's credential is stored in the resource yaml file and I want to provide them using secrets or vault by HashiCorp. 

I can't figure out the proper way to read/provide my user from secrets or vault.

Anyone can help? Thanks

activemq-artemis-operator: v1.0.5

```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisSecurity
metadata:
  name: amq-security
spec:
  loginModules:
    propertiesLoginModules:
    - name: 'prop-module'
      users:
      - name: user1
        password: pa$$w0rd7!
        roles:
        - root
        - admin
  securityDomains:
    brokerDomain:
      name: 'activemq'
      loginModules:
      - name: 'prop-module'
        flag: 'sufficient'
```
