### ISSUE TITLE
Artemis broker instance fails to start due to an invalid "broker.properties" file path in JAVA_OPTS

### ISSUE THREAD

**Issue by vkwiley** [artemiscloud/activemq-artemis-operator#452]
**Describe the bug**
Artemis broker instance fails to start due to an invalid broker.properties file path

**To Reproduce**
Deploy ActiveMQArtemis object with Operator versions starting from 1.0.6

**Platform (please complete the following information):**
 - AWS EKS (vanilla EKS image)

**Additional context**
Logs:

2023-01-15 04:52:36,075 ERROR [org.apache.activemq.artemis.core.server] AMQ224097: Failed to start server: java.io.FileNotFoundException: /amq/extra/configmaps/rex-artemis-backup-props (Is a directory)

Faulty code is probably [this line](https://github.com/artemiscloud/activemq-artemis-operator/blob/main/controllers/activemqartemis_reconciler.go#L1886) (missing /broker.properties)

**Comment by brusdev** [comment]
@vkwiley could you provide an ActiveMQArtemis CR to reproduce this issue?

**Comment by gtully** [comment]
hmm, this is due to brokerProperties being mutable and the broker accepting a -properties arg that is a directory.
the change is: https://github.com/artemiscloud/activemq-artemis-operator/commit/8f8624a97d0c8fe55465464bf540fac9eee5bdbf#diff-32e4c985bb650a7028cf649306e140d1cf176b91d4f36dbfbce53083d0f63bd6R1675

it looks like the broker image does not have the corresponding change to support a directory rather than a file.
the change is in 2.27.1

https://github.com/apache/activemq-artemis/commit/7bc3b0280946811a65e6019f0e1ccba98097bf47

I think the fix is to use both JAVA_OPTS and JAVA_ARGS_APPEND - JAVA_ARGS_APPEND is only in 2.27.1 and can override the JAVA_OPTS to provide the required directory configuration.

https://github.com/apache/activemq-artemis/blob/2.27.1/artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis#L117

**Comment by vkwiley** [comment]
@brusdev  here is the manifest
`apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: qa
spec:
  acceptors:
  - name: artemis
    port: 61616
    protocols: core,amqp,stomp
  adminPassword: XXXXXX
  adminUser: XXXXXXX
  deploymentPlan:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: ActiveMQArtemis
              operator: In
              values:
              - artemis-broker
          namespaces:
          - qa
          topologyKey: topology.kubernetes.io/zone
    clustered: true
    extraMounts:
      secrets:
      - dynatrace
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.7
    initImage: XXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/artemis-init:311.0-f977421b #a custom init image, adds some dynatrace monitoring support
    labels:
      app: artemis-broker-app
    messageMigration: true
    persistenceEnabled: true
    podSecurityContext:
      fsGroup: 185
    requireLogin: true
    resources:
      limits:
        cpu: 2000m
        memory: 6Gi
      requests:
        cpu: 800m
        memory: 2Gi
    size: 2
    storage:
      size: 20Gi
      storageClassName: gp3
`

Artemis version is 2.23 there. When used with operator version 1.0.6 artemis starts to give the error mentioned above

**Comment by brusdev** [comment]
@vkwiley thanks, I'm able to reproduce this issue with your CR removing the storage and using operator version 1.0.6:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: default
spec:
  acceptors:
  - name: artemis
    port: 61616
    protocols: core,amqp,stomp
  adminPassword: admin
  adminUser: admin
  deploymentPlan:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: ActiveMQArtemis
              operator: In
              values:
              - artemis-broker
          namespaces:
          - default
          topologyKey: topology.kubernetes.io/zone
    clustered: true
    extraMounts:
      secrets:
      - dynatrace
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.8
    initImage: quay.io/artemiscloud/activemq-artemis-broker-init:1.0.8
    labels:
      app: artemis-broker-app
    messageMigration: true
    persistenceEnabled: true
    podSecurityContext:
      fsGroup: 185
    requireLogin: true
    resources:
      limits:
        cpu: 2000m
        memory: 6Gi
      requests:
        cpu: 800m
        memory: 2Gi
    size: 2
```
