### ISSUE TITLE
Possibility to install the operator in OLM modes "AllNamespaces" & "MultiNamespace"

### ISSUE THREAD

**Issue by mhofstetter** [artemiscloud/activemq-artemis-operator#46]
**Is your feature request related to a problem? Please describe.**
Currently, the operator only supports the OLM "OwnNamespace" mode and therefore needs to be installed / deployed in each namespace where someone wants to deploy an ActiveMQ Artemis broker. This is quite an operational overhead.

**Describe the solution you'd like**
It should be possible to install the operator in the OLM modes `AllNamespaces` & `MultiNamespace` to get rid of managing multiple operator instances in the same cluster.

https://olm.operatorframework.io/docs/concepts/crds/operatorgroup/#installmodes-and-supported-operatorgroups

**Additional context**
* The OLM annotations in combination with K8s downward API should be used to pass the operator namespace & watched / target namespaces into the operator pod.

e.g.
```
            - name: NAMESPACES
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.annotations[''olm.targetNamespaces'']'
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.annotations[''olm.operatorNamespace'']'
```

* The operator should distinguish between the Operator Namespace and its Target / Watched namespaces. This is currently mixed in the code. (e.g. when using the watchnamespace for the service account lookup (https://github.com/artemiscloud/activemq-artemis-operator/blob/master/cmd/manager/main.go#L122) -> Use `k8sutil.GetOperatorNamespace()`))
* The current limitation to install an ActiveMQ Artemis broker only once per namespace needs to be implemented differently (https://github.com/artemiscloud/activemq-artemis-operator/blob/master/pkg/controller/broker/v2alpha4/activemqartemis/activemqartemis_controller.go#L147) Currently this implementation would prevent an "AllNamespaces" operator from creating multiple ActiveMQArtemis instances even though they would be in different namespaces.
