### ISSUE TITLE
Add doc for JVM metrics

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#466]
JVM memory metrics are enabled by default, add doc to describe how to use the `spec.brokerProperties` field to enable JVM GC and threads metrics, i.e.

```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-jvm
spec:
  console:
    expose: true
  deploymentPlan:
    size: 1
    enableMetricsPlugin: true
  brokerProperties:
    - "metricsConfiguration.jvmGc=true"
    - "metricsConfiguration.jvmMemory=true"
    - "metricsConfiguration.jvmThread=true"
```
