### ISSUE TITLE
Support custom host domains

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#472]
Add a field to the ActiveMQArtemis CRD to customize the domain used by the IngressController, i.e. to expose the console with a subdomain of my.domain.com
```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 1
  publicDomain: my.domain.com
  console:
    expose: true
```
