### ISSUE TITLE
No LoginModule found for org.keycloak.adapters.jaas.DirectAccessGrantsLoginModule

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#476]
The broker pod raises the following warning when keycloak login module is used:
```
[io.hawt.system.Authenticator] Login failed due to: No LoginModule found for org.keycloak.adapters.jaas.DirectAccessGrantsLoginModule
```

- Apply the following yaml:
```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 1
    image: placeholder
---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisSecurity
metadata:
  name: keycloak-login
spec:
  loginModules:
    keycloakLoginModules:
    - name: 'keycloak-broker'
      moduleType: 'directAccess'
      configuration:
        realm: 'activemq'
        resource: 'artemis-broker'
        authServerUrl: 'http://KEYCLOAK_SVC_IP:8080/auth'
        useResourceRoleMappings: true
        principalAttribute: 'preferred_username'
        sslRequired: 'external'
        credentials:
        - key: 'secret'
          value: 'KEYCLOAK_CLIENT_SECRET'
  securityDomains:
    brokerDomain:
      name: "activemq"
      loginModules:
        - name: "keycloak-broker"
          flag: "sufficient"
```
Produce messages:
```
./amq-broker/bin/artemis producer --verbose --destination queue://test --user admin --password admin --url tcp://artemis-broker-ss-0.artemis-broker-hdls-svc.default.svc.cluster.local:61616
```
