### ISSUE TITLE
Operator upgarde doesn't work as expected

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#505]
**Describe the bug**
The broker container image is updated also if the `spec.upgardes.enabled` property is false.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata: 
  name: ex-aao
spec: 
  deploymentPlan: 
    image: placeholder
    size: 1
  upgrades: 
    enabled: false
    minor: false
```

**To Reproduce**
1. Install the operator version v1.0.7
2. Deploy a basic ActiveMQArtemis CR
3. Check the broker container image is quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.11
4. Update the operator to version v1.0.10
3. Check the broker container image is quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.14

**Expected behavior**
The broker container image should not change if the `spec.upgardes.enabled` property is false.
