### ISSUE TITLE
Support custom annotations and labels for all resources created by the operator

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#588]
The operator supports custom annotations and labels for the pods related to the ActiveMQArtemis CRs by setting the `spec.deploymentPlan.annotations` and `spec.deploymentPlan.labels` fields.

Prefixes could be use in the keys to apply annotations and labels to a specific resource type, i.e. the prefix  `io.artemiscloud.ingress.annotation/` could be used to apply annotations to ingress resources:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker-resources
spec:
  deploymentPlan:
    labels:
      io.artemiscloud.ingress.annotation/foo: too
```

**Comment by gtully** [comment]
would it just be? 
labels:
      io.artemiscloud.ingress/foo: too

where label or annotation is implicit. First forward slash delimits.

**Comment by brusdev** [comment]
I like the char `@` to identify the item name +1

**Comment by brusdev** [comment]
I was thinking that maybe the ActiveMQArtemis CR should have the field `labels` in acceptor, connector and console too

**Comment by joshdreagan** [comment]
One additional suggestion would be to add the ability to use templates in the annotations. Doing so would allow for easy integration with skupper. 

For example:

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  acceptors:
    - name: amqp
      port: 5672
      protocols: amqp 
      annotations:
        - skupper.io/address: "artemis-broker-amqp-${STATEFUL_SET_ORDINAL}-svc-dc1"
        - skupper.io/port: "5672"
        - skupper.io/proxy: "tcp"
```

Possibly also allow for specifying annotations that only apply to certain members of the StatefulSet.
