### ISSUE TITLE
Omit Reason for Status=true conditions in our status subresource

### ISSUE THREAD

**Issue by gtully** [artemiscloud/activemq-artemis-operator#596]
the true reason text in our conditions is really a duplicate, Valid=true Reason=Validation Succeeded,  BrokerPropertiesApplied=true Reason=Applied.. not giving us any additional value.

As a general rule, it makes sense to omit the reason when status==true to keep the conditions and status as simple as possible.
If we find an exception, we can of course add the Reason!

**Comment by brusdev** [comment]
@gtully in [Kubernetes API Conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties) I see `This field may not be empty.` that should mean it is often empty.

**Comment by gtully** [comment]
Well that puts an end to this idea, thanks for peeking!
We may be stuck with the duplication, Valid=true Reason=ValidationSucceeded

maybe it is not too bad!

**Comment by gtully** [comment]
ah, sorry i misread, it is reasonable to use the empty string in the true case. it is just that it needs some value.
see: https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L1523

**Comment by gtully** [comment]
The api server validates that the string has size > 1
`  2023-05-26T12:18:47.803+0100  ERROR   package k8s_actions     Failed to update status on *v1beta1.ActiveMQArtemis     {"ActiveMQArtemis Name": "aa-controller1614a", "Namespace": "default", "error": "ActiveMQArtemis.broker.amq.io \"aa-controller1614a\" is invalid: status.conditions.reason: Invalid value: \"\": status.conditions.reason in body should be at least 1 chars long"}
`
I am thinking maybe to use the value "Complete" or leave things as they are. An empty string won't work, I guess maybe " " a single space character, but that looks like something is missing. Which i is!

Thoughts?

**Comment by gtully** [comment]
now favouring " ", reason missing, because Ready=true with Reason=Completed is not sensible. Ready=true, Reason=" " is better. There is no reason, the condition being true is the reason!

**Comment by gtully** [comment]
but that too is skuppered `  2023-05-26T13:40:15.215+0100	ERROR	Reconciler error	{"controller": "activemqartemis", "controllerGroup": "broker.amq.io", "controllerKind": "ActiveMQArtemis", "ActiveMQArtemis": {"name":"aa-controller627f","namespace":"default"}, "namespace": "default", "name": "aa-controller627f", "reconcileID": "2ac5dcbf-09b2-426d-b82d-17f284ebeefd", "error": "ActiveMQArtemis.broker.amq.io \"aa-controller627f\" is invalid: status.conditions[0].reason: Invalid value: \" \": status.conditions[0].reason in body should match '^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$'"}
`

maybe it needs to be a smiley face  (U+1F60A)

**Comment by brusdev** [comment]
Deployment conditions:
```
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-05-26T12:42:38Z'
      lastTransitionTime: '2023-05-26T12:42:38Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-05-26T12:43:18Z'
      lastTransitionTime: '2023-05-26T12:42:38Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "activemq-artemis-controller-manager-759c679d7" has
        successfully progressed.
```

Pod conditions
```
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-05-26T12:42:38Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-05-26T12:43:18Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-05-26T12:43:18Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-05-26T12:42:38Z'
```

@gtully  It seems pod conditions have no reasons and messages.
