### ISSUE TITLE
Register diverts for microservices using ArtemisMQ

### ISSUE THREAD

**Issue by bergner** [artemiscloud/activemq-artemis-operator#598]
**Is your feature request related to a problem? Please describe.**
Assume you have a K8s cluster with ArtemisMQ deployed using the operator. There are numerous services running in the cluster that want to use the MQ for messaging and it can vary from one installation to another what services are running. I would like to figure out a way for deployment of services A, B and C to "register" what they need from ArtemisMQ. Most events are sent as MULTICAST but several services want to have dedicated queues with ANYCAST behavior and hence want to setup diverts (with a suitable filter) to route relevant messages to their dedicated queue.

* The ActiveMQArtemisAddress CRD allows a service to register addresses. So dynamically registering queues used by services A/B/C is easy.
* Diverts can as far as I can tell be configured by:
  1. editing "brokerProperties" on the ActiveMQArtemis manifest similar to this example https://github.com/artemiscloud/activemq-artemis-operator/issues/160#issuecomment-1401712493
  2. by using an init container. This is quite messy and unless this init container also implements discovery of all the services it needs to generate configuration for you would end up having to rebuild the Artemis init container every time a new microservice is deployed or removed.

**Describe the solution you'd like**
Having the deployment of services A/B/C dynamically edit the "brokerProperties" feels fragile to me, especially since several of them are likely to start around the same time.  It might also be problematic from an RBAC point of view. I'm hoping to get some good suggestions here but these are ideas that I can think of:

1. Use a new ActiveMQArtemisDivert(s) CRD for defining divert(s).
2. Edit brokerProperties anyway
3. Have some mechanism for "including" snippets of configuration from ConfigMaps that have some Artemis annotation on them. The Artemis operator reconciles these config maps into a complete broker.xml. E.g. service A defines a ConfigMap with a "address.xml" and a "divert.xml" that declares what it needs and the operator includes them in a semantically sensible order. This means the operator would define what annotation to use and what file names in the ConfigMap mean like "address.xml" and "divert.xml".

Any ideas/suggestions on how to effectively manage a large (and somewhat variable) set of diverts are welcome.

**Comment by brusdev** [comment]
ActiveMQ Artemis already support multiple broker property files settings the urls with the system property `broker.properties`, i.e.

```
apiVersion: v1
kind: Secret
metadata:
  name: artemis-bp1
type: Opaque
stringData:
  broker.properties: |
    divertConfigurations.divert1.address=a1
    divertConfigurations.divert1.forwardingAddress=fa1
```

```
apiVersion: v1
kind: Secret
metadata:
  name: artemis-bp2
type: Opaque
stringData:
  broker.properties: |
    divertConfigurations.divert2.address=a2
    divertConfigurations.divert2.forwardingAddress=fa2
```

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-mbp
spec:
  brokerProperties:
    - "divertConfigurations.divert0.address=a0"
    - "divertConfigurations.divert0.forwardingAddress=fa0"
  deploymentPlan:
    extraMounts:
      secrets:
        - artemis-bp1
        - artemis-bp2
  env:
    - name: JAVA_ARGS_APPEND
      value: -Dbroker.properties=/amq/extra/secrets/artemis-mbp-props/broker.properties,/amq/extra/secrets/artemis-bp1/broker.properties,/amq/extra/secrets/artemis-bp2/broker.properties
```
