### ISSUE TITLE
Support custom ingress hosts

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#614]
Add the field `spec.ingressHost` to customize the host for Ingress and Route resources of the broker. The field `spec.ingressHost` also supports the following variables:
- $(CR_NAME) - the name of the custom resource
- $(CR_NAMESPACE) - the namespace of the custom resource
- $(BROKER_ORDINAL) - the StatefulSet ordinal index of the broker pod
- $(ITEM_NAME) - the name of the item (acceptor's name, connector's name or console)
- $(RES_TYPE) - the type of the resource (ing for Ingress and rte for Route)
- $(INGRESS_DOMAIN) - the value of the field `spec.ingressDomain`

The following ActiveMQArtemis CR generates the following acceptor, connector and console Ingress resources:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata: 
  name: ex-aoo
spec: 
  deploymentPlan: 
    size: 2
  acceptors: 
  - name: my-acceptor
    port: 61617
    sslEnabled: true
    expose: true
    ingressHost: $(CR_NAME)-$(ITEM_NAME)-$(BROKER_ORDINAL).$(INGRESS_DOMAIN)
  connectors: 
  - name: my-connector
    port: 61617
    sslEnabled: true
    expose: true
    ingressHost: $(CR_NAME)-$(ITEM_NAME)-$(BROKER_ORDINAL).$(INGRESS_DOMAIN)
  console: 
    name: my-console
    sslEnabled: true
    expose: true
    ingressHost: $(CR_NAME)-$(ITEM_NAME)-$(BROKER_ORDINAL).$(INGRESS_DOMAIN)
  ingressDomain: my-domain.com
```
```
ex-aoo-my-acceptor-0.my-domain.com
ex-aoo-my-acceptor-1.my-domain.com
```
```
ex-aoo-my-connector-0.my-domain.com
ex-aoo-my-connector-1.my-domain.com
```
```
ex-aoo-my-console-0.my-domain.com
ex-aoo-my-console-1.my-domain.com
```
