### ISSUE TITLE
cert-manager and trust-manager support for acceptors setup

### ISSUE THREAD

**Issue by bbroniewski** [artemiscloud/activemq-artemis-operator#636]
Hi,

Problem:
I want cert-manager and trust-manager to create and rotate keystore and truststore for broker acceptors.

How it could work:
1. Acceptor part of the broker CRD could accept providing secret with keystore generated by cert-manager
2. Acceptor part of the broker CRD could accept providing config map with truststore generated by trust-manager
3. Acceptor part of the broker CRD could accept providing secret with keystore and truststore passwords

Alternatives:
Could I just mount secret and configmap to some paths in the artemis broker cotnainer?
If yes could you tell paths, env variables to set?

Additional context:
cert-manager
https://cert-manager.io/

trust-manager
https://cert-manager.io/docs/projects/trust-manager/

**Comment by brusdev** [comment]
ArtemisCloud Operator supports custom keyStore and trustStore paths adding keyStorePath and trustStorePath entries to the acceptor secret, i.e. supposing the name of the secret created by certmanager is amq-cert-broker-secret, the solution is to create an acceptor secret with keyStorePath and trustStorePath entries and to define an extra mount for amq-cert-broker-secret:

```
oc create secret generic my-acceptor-secret \
--from-literal=keyStorePath=/amq/extra/secrets/amq-cert-finance-secret/keystore.jks \
--from-literal=trustStorePath=/amq/extra/secrets/amq-cert-finance-secret/truststore.jks \
--from-literal=keyStorePassword=<password> \
--from-literal=trustStorePassword=<password>
```

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
  application: ex-aao-app
spec:
  acceptors:
    - name: my-acceptor
      sslEnabled: true
      sslSecret: my-acceptor-secret
      ...
  deploymentPlan:
    extraMounts:
      secrets:
        - amq-cert-broker-secret
```
