### ISSUE TITLE
Authorisation does not work. login with any user, password possible

### ISSUE THREAD

**Issue by hupling** [artemiscloud/activemq-artemis-operator#640]
**Describe the bug**

![grafik](https://github.com/artemiscloud/activemq-artemis-operator/assets/11695964/d5c75a7f-c8e5-4039-b8c1-ad4ac1789080)

You can login with any username and password. Authorization doesn't work. This is a security problem

**Platform (please complete the following information):**
 - Red Hat Integration - AMQ Broker for RHEL 8 (Multiarch) 7.10.3-opr-1 provided by Red Hat

```yml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  acceptors:
    - name: broker-amq-tcp
      port: 61616
      protocols: all
  adminPassword: YBJtQ758wP
  adminUser: admin
  deploymentPlan:
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 1
```

even with this config it doesn't work

```yml
console:
    expose: true
    useClientAuth: true
```
