### ISSUE TITLE
Need complete Setup of Jolokia for accessing the api url for EKS cluster

### ISSUE THREAD

**Issue by gnaveen33** [artemiscloud/activemq-artemis-operator#696]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
Optional. A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Optional. Add any other context or screenshots about the feature request here.

**Comment by brusdev** [comment]
@gnaveen33 the broker pods enable the jolokia instance embedded in the console by default. You can use the field `deploymentPlan.jolokiaAgentEnabled` to enable a full jolokia agent.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
  application: ex-aao-app
spec:
  deploymentPlan:
    jolokiaAgentEnabled: true
```

**Comment by gnaveen33** [comment]
@brusdev, thanks for the response.
Now, how to access the jolokia api url

**Comment by gnaveen33** [comment]
in Active mq console,
under JMX tab i could see jolokia config info with attributes an operation info.
But I'm not able to see any other info for accessing API url.

can you please let me know on this.

**Comment by gnaveen33** [comment]
Thanks for update.
Any sample post call to create queue using this Jolokia api url?

**Comment by brusdev** [comment]
@gnaveen33 I would recommend you to use broker properties, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-addresses
spec:
  deploymentPlan:
    image: quay.io/dbruscin/amq7-amq-broker-rhel8:7.11
    initImage: quay.io/dbruscin/amq7-amq-broker-init-rhel8:7.11
  brokerProperties:
    - "addressConfigurations.test-address.routingTypes=ANYCAST"
    - "addressConfigurations.test-addressqueueConfigs.q1.address=Test2"
    - "addressConfigurations.test-address.queueConfigs.q1.routingType=ANYCAST"
    - "addressConfigurations.test-address.queueConfigs.q2.address=Test3"
    - "addressConfigurations.test-address.queueConfigs.q2.routingType=ANYCAST"
```

For specific questions related to Apache ActiveMQ Artemis, you could send an email to usersusers@activemq.apache.org
