### ISSUE TITLE
Allow configuring priorityClassName for broker deployment

### ISSUE THREAD

**Issue by KevinFrommeltAtFanatics** [artemiscloud/activemq-artemis-operator#837]
**Describe the feature**
Add the ability to configure the `priorityClassName` for the broker pods. We would like to be able to set the `priorityClassName` to something other than the default.

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by brusdev** [comment]
@KevinFrommeltAtFanatics you can customize the priorityClassName and other podSpec fields by using a strategic merge patch, for further details see [custom mods via a strategic merge patch](https://github.com/artemiscloud/activemq-artemis-operator/blob/1.1.0/docs/help/operator.md#custom-mods-via-a-strategic-merge-patch), i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata: 
  name: artemis-broker
spec:
  resourceTemplates:
    - selector:
        kind: StatefulSet
      patch:
        kind: StatefulSet
        spec:
          template:
            spec:
              priorityClassName: high-priority
```
