### ISSUE TITLE
The cert-manager certificates from annotations don't work

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#849]
**Describe the bug**
The cert-manager certificates from annotations are created after the deployment but the deploy fails because the manager check if the ssl secret exists:

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: aa-con-cer-man185a
spec:
  acceptors:
    - expose: true
      exposeMode: ingress
      ingressHost: aa-con-cer-man185a.tests.artemiscloud.io
      name: tls
      port: 61617
      sslEnabled: true
      sslSecret: aa-con-cer-man185a-tls-0-svc-ing-test-secret
  resourceTemplates:
    - selector:
        kind: Ingress
        name: aa-con-cer-man185a-tls-0-svc-ing
      annotations:
        cert-manager.io/issuer: aa-con-cer-man185a-issuer
      patch:
        kind: Ingress
        spec:
          tls:
            - hosts:
                - aa-con-cer-man185a.tests.artemiscloud.io
              secretName: aa-con-cer-man185a-tls-0-svc-ing-test-secret
```

```
status:
  conditions:
    - lastTransitionTime: '2024-04-04T08:50:58Z'
      message: required secret not exist aa-con-cer-man185a-tls-0-svc-ing-test-secret
      reason: ResourceError
      status: 'False'
      type: Deployed
```

> [!TIP]
> Vote this issue reacting with :+1: or :-1:
