### ISSUE TITLE
Expose the Management Console

### ISSUE THREAD

**Issue by petejturner** [artemiscloud/activemq-artemis-operator#904]
Hello All,

Loving this project.  Locally with minikube I am able to access the Management Console from localhost by defining a service.

We're debugging some issues in a deployed EKS cluster, and I would love to have access to the Management Console even for a short amount of time.  However, there are issues with CORS and it is unusable.

https://medium.com/@hasnat.saeed/setup-activemq-artemis-on-ubuntu-18-04-76bb4975308b

This article describes modifying bootstrap.xml and jolokia-access.xml to allow external access to the Management Console, is there a way to change these settings without deploying my own images?

Thank you very much.

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by brusdev** [comment]
Hi @petejturner, you can use an Ingress resource to expose the management console, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  console:
    expose: true
    exposeMode: ingress
    ingressHost: artemis-broker-console.my-domain.com
```
