### ISSUE TITLE
Expose the Management Console with Istio

### ISSUE THREAD

**Issue by win5923** [artemiscloud/activemq-artemis-operator#929]
**Describe the bug**
browser got `Failed to load resource: the server responded with a status of 503 ()`.

Pod log:
```
2024-05-17 08:31:21,168 INFO  [org.apache.activemq.artemis] AMQ241001: HTTP Server started at http://artemis-broker-ss-0.artemis-broker-hdls-svc.activemq-artemis-operator.svc.cluster.local:8161
2024-05-17 08:31:21,168 INFO  [org.apache.activemq.artemis] AMQ241002: Artemis Jolokia REST API available at http://artemis-broker-ss-0.artemis-broker-hdls-svc.activemq-artemis-operator.svc.cluster.local:8161/console/jolokia
2024-05-17 08:31:21,168 INFO  [org.apache.activemq.artemis] AMQ241004: Artemis Console available at http://artemis-broker-ss-0.artemis-broker-hdls-svc.activemq-artemis-operator.svc.cluster.local:8161/console
```

ActiveMQArtemis:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: activemq-artemis-operator
spec:
  acceptors:
    - name: activemq-mqtt
      expose: false
      port: 5672
      protocols: mqtt
      sslEnabled: true
      sslSecret: amq-ssl-secret

  deploymentPlan:
    size: 1
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.33.0
    enableMetricsPlugin: true
```

istio-gateway.yml:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - test1.cloudapp.azure.com
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - test1.cloudapp.azure.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        cipherSuites:
          - ECDHE-ECDSA-AES128-GCM-SHA256
          - ECDHE-RSA-AES128-GCM-SHA256
          - ECDHE-ECDSA-AES128-SHA
          - AES128-GCM-SHA256
          - AES128-SHA
          - ECDHE-ECDSA-AES256-GCM-SHA384
          - ECDHE-RSA-AES256-GCM-SHA384
          - ECDHE-ECDSA-AES256-SHA
          - AES256-GCM-SHA384
          - AES256-SHA
        credentialName: istio-cert-prod
        maxProtocolVersion: TLSV1_3
        minProtocolVersion: TLSV1_2
        mode: SIMPLE
```

VirtualService.yml:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: activemq-web-virtualservice
  namespace: activemq-artemis-operator
spec:
  gateways:
    - istio-system/istio-gateway
  hosts:
    - test1.cloudapp.azure.com
  http:
  - match:
    - uri:
        prefix: /activemq/
    rewrite:
      uri: /
    route:
      - destination:
          host: artemis-broker-ss-0.artemis-broker-hdls-svc.activemq-artemis-operator.svc.cluster.local
          port:
            number: 8161
```

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by win5923** [comment]
I change my gateway and virtual service to below, now I can see the Artemis console on browser:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: activemq-gateway
  namespace: activemq-artemis-operator
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: activemq-web-virtualservice
  namespace: activemq-artemis-operator
spec:
  gateways:
    # - istio-system/istio-gateway
    - activemq-gateway
  hosts:
    - "*"
  http:
  - match:
    - uri:
        prefix: /
    route:
      - destination:
          host: artemis-broker-hdls-svc.activemq-artemis-operator.svc.cluster.local
          port:
            number: 8161
```

But got so many error:
![image](https://github.com/artemiscloud/activemq-artemis-operator/assets/56353753/3d2f2a21-4dbc-4d45-905a-54397592cb7f)
