### ISSUE TITLE
Need to update Ingress endpoint url in acceptor 

### ISSUE THREAD

**Issue by gnaveen33** [artemiscloud/activemq-artemis-operator#930]
Hi Team,

How to change the default endpoint URL of acceptor to Ingress endpoint URL through Operator?

Regards,
Naveen

**Comment by brusdev** [comment]
@gnaveen33 you can customize the endpoint URL of an acceptor by using broker properties, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata: 
  name: broker
spec:
  acceptors:
    - name: my-acceptor
      port: 61626
  brokerProperties:
    - 'acceptorConfigurations.my-acceptor.params.host=my-host'
```

Why do you need to customize the endpoint URL of an acceptor?
