### ISSUE TITLE
addresses are not deleted when autoDeleteAddresses is true

### ISSUE THREAD

**Issue by AlexW00** [artemiscloud/activemq-artemis-operator#937]
**Describe the bug**

When configuring a broker to auto-delete expired addresses like this:

```yaml
# ...
  addressSettings:
    addressSetting:
      - match: '/tmp/#'
        expiryDelay: 300000
        autoDeleteAddresses: true
        autoDeleteAddressesDelay: 30000
        autoDeleteQueues: true
        autoDeleteCreatedQueues: true
        autoDeleteQueuesDelay: 30000
        autoDeleteQueuesMessageCount: -1
# ...
```

it

- correctly deletes automatically created, expired, queues
- **does not** delete automatically created, expired, addresses (e.g. named '/tmp/abc/123')

Further information:

I use the broker as a relay for STOMP websocket messaging (spring boot) and define an acceptor like this:
```yaml
  acceptors:
    - name: stomp
      port: 61613
      protocols: all
```

I also verified, that the addresses had queues / consumers / messages at least once.

When setting the artemis version (in broker yaml) to `version: 2.26.0`, it correctly deletes the queues as well as addresses.

Version info:
- broker: `activemq-artemis-broker-kubernetes@sha256:52f337cd5d7d5d199eebf4fc722f8c5279f652506f009efbc0f8f6de88e18718`
- artemiscloud: v1.2.1 (latest)

> [!TIP]
> Vote this issue reacting with :+1: or :-1:
