### ISSUE TITLE
Trust secret doesn't support bundle with additional format certificates

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#945]
**Describe the bug**
When the trust secret has additional format certificates, the broker pods are restarted frequently, i.e.

```
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: my-bundle
spec:
  sources:
  - secret:
      name: "my-foo-cert-secret"
      key: "tls.crt"
  - secret:
      name: "my-bar-cert-secret"
      key: "tls.crt"
  target:
    secret:
      key: "root-certs.pem"
    additionalFormats:
      jks:
        key: "bundle.jks"
      pkcs12:
        key: "bundle.p12"
```

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata: 
  name: broker
spec:
  acceptors:
    - name: tls-acceptor
      port: 61617
      sslEnabled: true
      needClientAuth: true
      sslSecret: my-broker-cert-secret
      trustSecret: my-bundle
```

> [!TIP]
> Vote this issue reacting with :+1: or :-1:
