### ISSUE TITLE
Broker properties from a secret key with the prefix broker- are not loaded

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#956]
**Describe the bug**
The broker properties from a secret key with the prefix `broker-` are not loaded, i.e.
```
kind: Secret
apiVersion: v1
metadata:
  name: my-secret-bp
data:
  broker-my-address.properties: >-  
    addressesSettings.my-address.managementMessageAttributeSizeLimit=-1
```

> [!TIP]
> Vote this issue reacting with :+1: or :-1:
