### ISSUE TITLE
Using ServiceMonitor with Prometheus Operator is not possible because of duplicate services with same labels

### ISSUE THREAD

**Issue by johgoe** [artemiscloud/activemq-artemis-operator#978]
My cluster contains configuration like this

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: active-mq-artemis-test
spec:
  deploymentPlan:
    enableMetricsPlugin: true
    size: 2
  acceptors:
    - name: http-core
      port: 61618
      protocols: CORE
```

which causes an additional service per broker node.

Because these services and hdls and the ping service contains the application label the following servicemonitor will cause duplicate scraper

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: artemis-with-metrics-monitor
spec:
  selector:
    matchLabels:
      application: active-mq-artemis-test
  endpoints:
  - targetPort: 8161
```

My cluster with 2 nodes are watched by 6 scrapers because of these. These are the labels shown in prometheus:

* container="active-mq-artemis-test-container" endpoint="8161" job="active-mq-artemis-test-ping-svc" namespace="activemq-artemis-operator-system" pod="active-mq-artemis-test-ss-0" service="active-mq-artemis-test-ping-svc"
* container="active-mq-artemis-test-container" endpoint="8161" job="active-mq-artemis-test-ping-svc" namespace="activemq-artemis-operator-system" pod="active-mq-artemis-test-ss-1" service="active-mq-artemis-test-ping-svc"
* container="active-mq-artemis-test-container" endpoint="8161" job="active-mq-artemis-test-http-core-0-svc" namespace="activemq-artemis-operator-system" pod="active-mq-artemis-test-ss-0" service="active-mq-artemis-test-http-core-0-svc"
* container="active-mq-artemis-test-container" endpoint="8161" job="active-mq-artemis-test-http-core-1-svc" namespace="activemq-artemis-operator-system" pod="active-mq-artemis-test-ss-1" service="active-mq-artemis-test-http-core-1-svc"
* container="active-mq-artemis-test-container" endpoint="8161" job="active-mq-artemis-test-hdls-svc" namespace="activemq-artemis-operator-system" pod="active-mq-artemis-test-ss-0" service="active-mq-artemis-test-hdls-svc"
* container="active-mq-artemis-test-container" endpoint="8161" job="active-mq-artemis-test-hdls-svc" namespace="activemq-artemis-operator-system" pod="active-mq-artemis-test-ss-1" service="active-mq-artemis-test-hdls-svc"

I guess currently there is no better way, but maybe an additional label like `app.kubernetes.io/component: headless` can be added and used within the serviceMonitor

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by johgoe** [comment]
@brusdev fyi, I saw you are currently writing an example how to use it.

**Comment by johgoe** [comment]
A workaround which works:

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: active-mq-artemis-test
  deploymentPlan:
    enableMetricsPlugin: true
    size: 2
  resourceTemplates:
    - selector:
        kind: "Service"
        name: "active-mq-artemis-test-hdls-svc"
      labels:
        app.kubernetes.io/component: headless


```

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: artemis-with-metrics-monitor
spec:
  selector:
    matchLabels:
      application: active-mq-artemis-test
      app.kubernetes.io/component: headless
  endpoints:
  - port: wconsj
```
