### ISSUE TITLE
ActiveMQArtemisAddress replacement into ActiveMQArtemis CRD through broker.properties 

### ISSUE THREAD

**Issue by khatib-moh** [artemiscloud/activemq-artemis-operator#983]
Hi,
I upgraded my activemq-artemis-operator deployed in GKE cluster into the latest version , I noticed that after the upgrade we found a warning :
```
Warning: The ActiveMQArtemisAddress CRD is deprecated. Use the spec.brokerProperties attribute in the ActiveMQArtemis CR to create addresses and queues instead.
``` 
my ActiveMQArtemisAddress configuration file looks like this:

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisAddress
metadata:
  name: artemis
spec:
  addressName: address_name
  password: #password
  queueConfiguration:
    purgeOnNoConsumers: true
  queueName: queuename
  removeFromBrokerOnDelete: true
  routingType: anycast
  user: admin

``` 
So I am trying to move the specs into the broker.properties of the ActiveMQArtemis as suggested in the above warning,

I went through the documentation as well as the example and I found these two attributes that could bu added to the broker.properities :

```
- addressConfigurations.myaddress-name.queueConfigs.myQueue0.address=myqueue 
- addressConfigurations.myaddress-name.queueConfigs.myQueue0.routingType=ANYCAST
 
``` 
If I am correct these two attributes can replace the below:

```
routingType: anycast
queueName: myqueue
``` 

so my question is , can you help with the reso of attributes? what is the equivalent inside the broker.properities ?
and where can I find them.

Thank you

**Comment by brusdev** [comment]
Hi @khatib-moh, the `user` and `password` fields of the ActiveMQArtemisAddress space are not required with the broker properties.

The `removeFromBrokerOnDelete` field is replaced by the `configDeleteAddresses` and `configDeleteQueues` fields in addressConfigurations, i.e.
```
- addressConfigurations.myaddress-name.configDeleteAddresses=FORCE
- addressConfigurations.myaddress-name.configDeleteQueues=FORCE
```

The `spec.queueConfiguration` fields like the `purgeOnNoConsumers` field can be replaced by the equivalent fields in the queueConfigs, i.e.
```
- addressConfigurations.myaddress-name.queueConfigs.myQueue0.purgeOnNoConsumers=true
```

**Comment by khatib-moh** [comment]
> Hi @khatib-moh, the `user` and `password` fields of the ActiveMQArtemisAddress space are not required with the broker properties.

Thank you so much for your help , So the only remaining thing now , is where can I set the user and password then?

**Comment by brusdev** [comment]
The username and password in `ActiveMQArtemisAddress` are only used by the operator to access the broker pods to create/delete the related address/queue. The operator doesn't need username ad password to apply the broker properties.

**Comment by khatib-moh** [comment]
Hi ,
I had this error while applying the new ACTIVEMQArtemis resource:

```
 message: 'some properties from artemis-release-name-mt-props resulted in error
        on pod artemis-release-name-mt-ss-0 : reasons: map[broker.properties:[{"value":"addressConfigurations.myaddress0.configDeleteAddresses=FORCE","reason":"java.lang.reflect.InvocationTargetException:
        No accessor method descriptor for: configDeleteAddresses on: class org.apache.activemq.artemis.core.config.CoreAddressConfiguration"},{"value":"addressConfigurations.myaddress0.configDeleteQueues=FORCE","reason":"java.lang.reflect.InvocationTargetException:
        No accessor method descriptor for: configDeleteQueues on: class org.apache.activemq.artemis.core.config.CoreAddressConfiguration"}]]'
``` 


this is my manifest file:

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis

spec:
  resourceTemplates:
   - selector:
       kind: "Service"

  ingressDomain: default 
  acceptors:
  - bindToAllInterfaces: false
    expose: true
    name: artemis
    port:PORT_NUMBER
    protocols: CORE,STOMP
  addressSettings:
    addressSetting:
    - autoCreateJmsQueues: true
      autoCreateJmsTopics: true
      enableMetrics: true
      match: activemq.management
    - autoCreateJmsQueues: true
      autoCreateJmsTopics: true
      autoDeleteAddresses: false
      autoDeleteQueues: false
      enableMetrics: true
      match: '#'
    - enableMetrics: true
      expiryAddress: PurgeCandidateQueue
      expiryDelay: 50400000
      match: ExpiryQueue
  adminPassword: password
  adminUser: admin
  brokerProperties:
  - addressConfigurations.my-address0.queueConfigs.myqueue.address=myqueue
  - addressConfigurations.my-address0.queueConfigs.myqueue.routingType=ANYCAST
  - addressConfigurations.my-address0.queueConfigs.myqueue.purgeOnNoConsumers=true
  - addressConfigurations.my-address0.configDeleteAddresses=FORCE
  - addressConfigurations.my-address0.configDeleteQueues=FORCE
  deploymentPlan:
    enableMetricsPlugin: true
    image: placeholder
    messageMigration: true
    persistenceEnabled: true
    podSecurityContext:
      fsGroup: 0
    size: 1

``` 
could you help?
