### ISSUE TITLE
Custom login module from -jaas-config extraMount doesn't working

### ISSUE THREAD

**Issue by john9x** [artemiscloud/activemq-artemis-operator#995]
**Describe the bug**
Hi!

Custom login module from -jaas-config extraMount doesn't working. `some_user` and `another_user` can't login to Artemis and I don't understand why.
I see mounted files in the pods and don't see any problems in the logs.
```
apiVersion: v1
kind: Secret
metadata:
  name: artemis-jaas-config
stringData:
  login.config: |
    activemq {
            // ensure the operator can connect to the broker by referencing the existing properties config
            org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
                org.apache.activemq.jaas.properties.user="artemis-users.properties"
                org.apache.activemq.jaas.properties.role="artemis-roles.properties"
                baseDir="/home/jboss/amq-broker/etc";

            org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
                reload=true
                org.apache.activemq.jaas.properties.user="users.properties"
                org.apache.activemq.jaas.properties.role="roles.properties";

    };

  users.properties: |
    some_user = pass
    another_user = pass

  roles.properties: |
    admin = admin, some_user 
    some_role = another_user 

---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 2
    persistenceEnabled: true
    messageMigration: true
    requireLogin: true
    extraMounts:
      - secrets:
          - artemis-jaas-config
```

This works fine but with deprecation warning.
```
---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisSecurity
metadata:
  name: artemis-security
spec:
  applyToCrNames:
    - "*"
  securityDomains:
    brokerDomain:
      name: 'activemq'
      loginModules:
        - name: "artemis-users"
          flag: sufficient
          reload: true
  loginModules:
    propertiesLoginModules:
      - name: "artemis-users"
        users:
          - name: some_user
            password: pass
            roles:
              - admin
          - name: another_user
            password: pass
            roles:
              - some_role
```

Also I can't find any docs how to use `spec.brokerProperties` to configure security settings like this
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisSecurity
metadata:
  name: artemis-security
spec:
  securitySettings:
    broker:
      - match: "#"
        permissions:
          - operationType: createNonDurableQueue
            roles:
              - admin
          - operationType: deleteNonDurableQueue
            roles:
              - admin
          - operationType: createDurableQueue
            roles:
              - admin
          - operationType: deleteDurableQueue
            roles:
              - admin
          - operationType: createAddress
            roles:
              - admin
          - operationType: deleteAddress
            roles:
              - admin
          - operationType: consume
            roles:
              - admin
          - operationType: browse
            roles:
              - admin
          - operationType: send
            roles:
              - admin
          - operationType: manage
            roles:
              - admin
```

> [!TIP]
> Vote this issue reacting with :+1: or :-1:
